<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="POS helps small businesses manage sales, inventory, products, and teams from one simple point-of-sale system.">
    <meta name="robots" content="index, follow, max-image-preview:large">
    <meta name="theme-color" content="#0f766e">
    <link rel="canonical" href="{{ url('/') }}">
    <link rel="icon" href="{{ asset('favicon.svg') }}" type="image/svg+xml">
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=dm-sans:400,500,600,700&family=fraunces:600,700&display=swap" rel="stylesheet">
    <meta property="og:type" content="website">
    <meta property="og:site_name" content="{{ config('app.name', 'POS') }}">
    <meta property="og:title" content="{{ config('app.name', 'POS') }} | Simple point of sale and inventory management">
    <meta property="og:description" content="Run sales, stock, products, and teams from one straightforward POS system.">
    <meta property="og:url" content="{{ url('/') }}">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:title" content="{{ config('app.name', 'POS') }} | Simple point of sale and inventory management">
    <meta name="twitter:description" content="Run sales, stock, products, and teams from one straightforward POS system.">
    <title>{{ config('app.name', 'POS') }} | Simple point of sale and inventory management</title>
    <script type="application/ld+json">{!! json_encode(['@context' => 'https://schema.org', '@type' => 'SoftwareApplication', 'name' => config('app.name', 'POS'), 'applicationCategory' => 'BusinessApplication', 'operatingSystem' => 'Web', 'description' => 'A point-of-sale and inventory management system for small businesses.', 'url' => url('/')], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) !!}</script>
    <style>
        :root { --ink:#102a2a; --muted:#54706d; --line:#d9e8e5; --teal:#0f766e; --mint:#d7f3ed; --cream:#f8fbf8; }
        * { box-sizing:border-box; } html { scroll-behavior:smooth; } body { margin:0; color:var(--ink); background:var(--cream); font-family:'DM Sans',system-ui,sans-serif; } a { color:inherit; text-decoration:none; } .shell { width:min(1120px, calc(100% - 40px)); margin:auto; }
        .nav { display:flex; align-items:center; justify-content:space-between; padding:23px 0; } .brand { display:flex; gap:10px; align-items:center; font-size:1.15rem; font-weight:700; letter-spacing:-.03em; } .mark { display:grid; place-items:center; width:32px; height:32px; background:var(--teal); color:#fff; border-radius:10px; font-size:18px; } .nav-links { display:flex; align-items:center; gap:26px; color:var(--muted); font-size:.92rem; font-weight:600; }
        .button { display:inline-flex; align-items:center; justify-content:center; border-radius:9px; padding:12px 18px; font-weight:700; font-size:.94rem; transition:.18s ease; } .button:hover { transform:translateY(-2px); } .button-primary { color:#fff; background:var(--teal); box-shadow:0 8px 20px #0f766e33; } .button-secondary { color:var(--teal); border:1px solid #a9d5cf; background:#fff; }
        .hero { display:grid; grid-template-columns:1.04fr .96fr; align-items:center; gap:68px; padding:75px 0 100px; } .eyebrow { display:inline-flex; align-items:center; gap:8px; border:1px solid #b5ded8; background:#ebfaf7; border-radius:999px; padding:7px 11px; color:#12635e; font-size:.78rem; font-weight:700; } .eyebrow i { width:7px; height:7px; border-radius:50%; background:#16a34a; }
        h1 { max-width:650px; margin:20px 0; font-family:Fraunces,Georgia,serif; font-size:clamp(2.7rem, 5.2vw, 4.7rem); line-height:1.02; letter-spacing:-.055em; } .lead { max-width:550px; margin:0; color:var(--muted); line-height:1.65; font-size:1.12rem; } .actions { display:flex; flex-wrap:wrap; gap:12px; margin-top:30px; } .proof { display:flex; gap:22px; margin-top:28px; color:#52716d; font-size:.84rem; font-weight:600; } .proof span::before { content:'✓'; margin-right:7px; color:#148176; font-weight:800; }
        .dashboard { position:relative; padding:17px; background:#fff; border:1px solid #d2e7e3; border-radius:20px; box-shadow:0 28px 60px #1b4d4820; transform:rotate(2deg); } .dashboard::before { content:''; position:absolute; z-index:-1; inset:20px -15px -15px 20px; border-radius:20px; background:#bde9df; } .screen { overflow:hidden; border:1px solid #e1ecea; border-radius:12px; } .screen-bar { display:flex; align-items:center; gap:5px; height:40px; padding:0 13px; background:#f8fbfa; border-bottom:1px solid #e4efec; } .dot { width:7px; height:7px; border-radius:50%; background:#b8ceca; }.dot:first-child{background:#ef8b84}.dot:nth-child(2){background:#edc266}.dot:nth-child(3){background:#65b99b}
        .screen-body { display:grid; grid-template-columns:74px 1fr; min-height:315px; background:#fff; } .side { padding:18px 13px; background:#fbfdfc; border-right:1px solid #edf3f1; }.side b { display:block; height:8px; margin-bottom:17px; border-radius:5px; background:#dcebe8; }.side b:first-child{background:#52a99d} .workspace { padding:22px; }.screen-title { width:112px; height:14px; background:#16413d; border-radius:4px; }.screen-sub { width:75px; height:7px; margin-top:9px; background:#d2e5e1; border-radius:4px; }
        .stats { display:grid; grid-template-columns:repeat(3, 1fr); gap:9px; margin-top:23px; }.stat { padding:11px; border:1px solid #e7f0ee; border-radius:8px; }.stat small { display:block; color:#7b9792; font-size:8px; }.stat strong { display:block; margin-top:7px; font-size:13px; }.up { color:#0b8d62; font-size:8px; } .bars { display:flex; align-items:end; gap:8px; height:95px; margin-top:18px; padding:13px; background:#f7fbfa; border-radius:9px; }.bars i { display:block; flex:1; border-radius:4px 4px 0 0; background:#8ed4c8; }.bars i:nth-child(2), .bars i:nth-child(5){background:#148176}.bars i:nth-child(1){height:38%}.bars i:nth-child(2){height:71%}.bars i:nth-child(3){height:50%}.bars i:nth-child(4){height:82%}.bars i:nth-child(5){height:93%}.bars i:nth-child(6){height:64%}
        .features { padding:82px 0; background:#fff; border-top:1px solid var(--line); }.section-intro { max-width:610px; }.kicker { color:#08776e; font-size:.8rem; font-weight:800; letter-spacing:.08em; text-transform:uppercase; }.features h2,.cta h2 { margin:11px 0; font-family:Fraunces,Georgia,serif; font-size:clamp(2rem,3.4vw,3rem); letter-spacing:-.04em; }.section-intro p { color:var(--muted); line-height:1.6; } .grid { display:grid; grid-template-columns:repeat(3,1fr); gap:16px; margin-top:35px; }.feature { padding:25px; border:1px solid var(--line); border-radius:14px; background:#fcfefd; }.feature-icon { display:grid; place-items:center; width:38px; height:38px; border-radius:10px; background:var(--mint); color:#076f66; font-weight:800; }.feature h3 { margin:17px 0 8px; font-size:1.05rem; }.feature p { margin:0; color:var(--muted); font-size:.92rem; line-height:1.58; }
        .cta { padding:82px 0; text-align:center; }.cta p { max-width:500px; margin:0 auto 23px; color:var(--muted); line-height:1.6; }.footer { padding:25px 0 35px; border-top:1px solid var(--line); color:#66807c; font-size:.86rem; }.footer .shell { display:flex; justify-content:space-between; } @media (max-width:760px) { .nav-links a:not(.button){display:none}.hero{grid-template-columns:1fr;gap:45px;padding:52px 0 70px}.dashboard{max-width:500px;margin:auto}.grid{grid-template-columns:1fr}.proof{gap:12px;flex-direction:column}.footer .shell{gap:9px;flex-direction:column}.screen-body{min-height:265px} }
    </style>
</head>
<body>
    <header class="shell nav"><a class="brand" href="{{ route('home') }}" aria-label="{{ config('app.name', 'POS') }} home"><span class="mark">▣</span>{{ config('app.name', 'POS') }}</a><nav class="nav-links" aria-label="Main navigation"><a href="#features">Features</a>@auth <a href="{{ route('dashboard') }}" class="button button-primary">Open dashboard</a> @else <a href="{{ route('login') }}">Log in</a><a href="{{ route('register') }}" class="button button-primary">Get started</a> @endauth</nav></header>
    <main><section class="shell hero" aria-labelledby="hero-heading"><div><span class="eyebrow"><i></i> Built for growing local businesses</span><h1 id="hero-heading">Run your shop with clarity, not clutter.</h1><p class="lead">{{ config('app.name', 'POS') }} brings your sales, inventory, products, and team together in one straightforward point-of-sale system.</p><div class="actions">@auth <a class="button button-primary" href="{{ route('dashboard') }}">Open your dashboard →</a> @else <a class="button button-primary" href="{{ route('register') }}">Create your account →</a><a class="button button-secondary" href="#features">Explore features</a> @endauth</div><div class="proof"><span>Fast checkout</span><span>Live inventory</span><span>Team-ready</span></div></div>
    <div class="dashboard" aria-label="An illustration of the {{ config('app.name', 'POS') }} sales dashboard"><div class="screen"><div class="screen-bar"><i class="dot"></i><i class="dot"></i><i class="dot"></i></div><div class="screen-body"><aside class="side"><b></b><b></b><b></b><b></b></aside><div class="workspace"><div class="screen-title"></div><div class="screen-sub"></div><div class="stats"><div class="stat"><small>Today's sales</small><strong>₱12,480</strong><span class="up">↑ 12%</span></div><div class="stat"><small>Orders</small><strong>48</strong><span class="up">↑ 8%</span></div><div class="stat"><small>Low stock</small><strong>6</strong><span class="up">View items</span></div></div><div class="bars"><i></i><i></i><i></i><i></i><i></i><i></i></div></div></div></div></div></section>
    <section id="features" class="features" aria-labelledby="features-heading"><div class="shell"><div class="section-intro"><span class="kicker">Everything in one place</span><h2 id="features-heading">The essentials your counter needs.</h2><p>Keep daily operations moving with practical tools designed around the way small retail teams actually work.</p></div><div class="grid"><article class="feature"><div class="feature-icon">↗</div><h3>Quick checkout</h3><p>Build orders and complete sales without slowing down the queue.</p></article><article class="feature"><div class="feature-icon">▤</div><h3>Inventory control</h3><p>Track stock movements and spot items that need attention before they run out.</p></article><article class="feature"><div class="feature-icon">◌</div><h3>Clear reporting</h3><p>See sales performance and product activity in a dashboard your team can understand.</p></article></div></div></section>
    <section class="cta"><div class="shell"><span class="kicker">Start simply</span><h2>Spend less time managing the shop.</h2><p>Set up your products, invite your team, and keep every sale and stock update in view.</p>@guest <a class="button button-primary" href="{{ route('register') }}">Get started with {{ config('app.name', 'POS') }} →</a> @endguest</div></section></main>
    <footer class="footer"><div class="shell"><span>© {{ now()->year }} {{ config('app.name', 'POS') }}. All rights reserved.</span><a href="{{ route('login') }}">Log in</a></div></footer>
</body>
</html>
