<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="POS helps small businesses manage sales, inventory, products, and teams from one simple point-of-sale system.">
    <meta name="robots" content="index, follow, max-image-preview:large">
    <meta name="theme-color" content="#0f766e">
    <link rel="canonical" href="{{ url('/') }}">
    <link rel="icon" href="{{ asset('favicon.svg') }}" type="image/svg+xml">
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=dm-sans:400,500,600,700&family=fraunces:600,700&display=swap" rel="stylesheet">
    <meta property="og:type" content="website">
    <meta property="og:site_name" content="{{ config('app.name', 'POS') }}">
    <meta property="og:title" content="{{ config('app.name', 'POS') }} | Simple point of sale and inventory management">
    <meta property="og:description" content="Run sales, stock, products, and teams from one straightforward POS system.">
    <meta property="og:url" content="{{ url('/') }}">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:title" content="{{ config('app.name', 'POS') }} | Simple point of sale and inventory management">
    <meta name="twitter:description" content="Run sales, stock, products, and teams from one straightforward POS system.">
    <title>{{ config('app.name', 'POS') }} | Simple point of sale and inventory management</title>
    <script type="application/ld+json">{!! json_encode(['@context' => 'https://schema.org', '@type' => 'SoftwareApplication', 'name' => config('app.name', 'POS'), 'applicationCategory' => 'BusinessApplication', 'operatingSystem' => 'Web', 'description' => 'A point-of-sale and inventory management system for small businesses.', 'url' => url('/')], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) !!}</script>
    <style>
        :root { --ink:#102a2a; --muted:#54706d; --line:#d9e8e5; --teal:#0f766e; --mint:#d7f3ed; --cream:#f8fbf8; }
        * { box-sizing:border-box; } html { scroll-behavior:smooth; } body { margin:0; color:var(--ink); background:var(--cream); font-family:'DM Sans',system-ui,sans-serif; } a { color:inherit; text-decoration:none; } .shell { width:min(1120px, calc(100% - 40px)); margin:auto; }
        .nav { display:flex; align-items:center; justify-content:space-between; padding:23px 0; } .brand { display:flex; gap:10px; align-items:center; font-size:1.15rem; font-weight:700; letter-spacing:-.03em; } .mark { display:grid; place-items:center; width:32px; height:32px; background:var(--teal); color:#fff; border-radius:10px; font-size:18px; } .nav-links { display:flex; align-items:center; gap:26px; color:var(--muted); font-size:.92rem; font-weight:600; }
        .button { display:inline-flex; align-items:center; justify-content:center; border-radius:9px; padding:12px 18px; font-weight:700; font-size:.94rem; transition:.18s ease; } .button:hover { transform:translateY(-2px); } .button-primary { color:#fff; background:var(--teal); box-shadow:0 8px 20px #0f766e33; } .button-secondary { color:var(--teal); border:1px solid #a9d5cf; background:#fff; }
        .hero { display:grid; grid-template-columns:1.04fr .96fr; align-items:center; gap:68px; padding:75px 0 100px; } .eyebrow { display:inline-flex; align-items:center; gap:8px; border:1px solid #b5ded8; background:#ebfaf7; border-radius:999px; padding:7px 11px; color:#12635e; font-size:.78rem; font-weight:700; } .eyebrow i { width:7px; height:7px; border-radius:50%; background:#16a34a; }
        h1 { max-width:650px; margin:20px 0; font-family:Fraunces,Georgia,serif; font-size:clamp(2.7rem, 5.2vw, 4.7rem); line-height:1.02; letter-spacing:-.055em; } .lead { max-width:550px; margin:0; color:var(--muted); line-height:1.65; font-size:1.12rem; } .actions { display:flex; flex-wrap:wrap; gap:12px; margin-top:30px; } .proof { display:flex; gap:22px; margin-top:28px; color:#52716d; font-size:.84rem; font-weight:600; } .proof span::before { content:'✓'; margin-right:7px; color:#148176; font-weight:800; }
        .dashboard { position:relative; margin:0; padding:15px; background:#fff; border:1px solid #d2e7e3; border-radius:20px; box-shadow:0 28px 60px #1b4d4820; transform:rotate(2deg); } .dashboard::before { content:''; position:absolute; z-index:-1; inset:20px -15px -15px 20px; border-radius:20px; background:#bde9df; } .screen { overflow:hidden; border:1px solid #e1ecea; border-radius:12px; background:#fff; } .product-bar { display:flex; align-items:center; justify-content:space-between; height:42px; padding:0 13px; background:#fff; border-bottom:1px solid #e4efec; } .product-brand { display:flex; align-items:center; gap:6px; color:#16413d; font-size:10px; font-weight:800; }.product-brand span { display:grid; place-items:center; width:17px; height:17px; border-radius:5px; background:#0f766e; color:#fff; font-size:10px; }.product-user { width:19px; height:19px; border-radius:50%; background:#d7f3ed; }
        .screen-body { display:grid; grid-template-columns:92px 1fr; min-height:315px; } .side { padding:13px 9px; background:#fbfdfc; border-right:1px solid #edf3f1; }.side a { display:flex; align-items:center; gap:6px; margin:2px 0; padding:7px 6px; border-radius:5px; color:#75918d; font-size:7px; font-weight:700; }.side a::before { content:''; width:6px; height:6px; border-radius:2px; background:#c9ddda; }.side a.active { background:#dff4ef; color:#0f766e; }.side a.active::before { background:#0f766e; } .workspace { padding:17px; background:#fff; }.workspace-head { display:flex; align-items:flex-start; justify-content:space-between; }.screen-title { color:#16413d; font-size:15px; font-weight:800; letter-spacing:-.03em; }.screen-sub { margin-top:3px; color:#8aa39f; font-size:7px; }.date-chip { padding:5px 7px; border:1px solid #d9e8e5; border-radius:5px; color:#54706d; font-size:6px; font-weight:700; }
        .stats { display:grid; grid-template-columns:repeat(4, 1fr); gap:7px; margin-top:15px; }.stat { min-width:0; padding:9px; border:1px solid #e1eeeb; border-radius:7px; }.stat small { display:block; overflow:hidden; color:#7b9792; font-size:6px; text-overflow:ellipsis; white-space:nowrap; }.stat strong { display:block; margin-top:5px; color:#16413d; font-size:10px; }.up { display:block; margin-top:3px; color:#0b8d62; font-size:6px; font-weight:700; }.stock-alert { border-color:#f0d7a6; background:#fffaf0; }.stock-alert .up { color:#a35b06; } .activity { margin-top:12px; border:1px solid #e1eeeb; border-radius:7px; overflow:hidden; }.activity h3 { margin:0; padding:8px 9px; border-bottom:1px solid #eaf2f0; color:#16413d; font-size:8px; }.activity-row { display:flex; align-items:center; gap:7px; padding:7px 9px; border-bottom:1px solid #eef5f3; }.activity-row:last-child { border:0; }.activity-icon { width:15px; height:15px; border-radius:4px; background:#d7f3ed; }.activity-copy { flex:1; }.activity-copy b,.activity-copy span { display:block; }.activity-copy b { color:#315a55; font-size:7px; }.activity-copy span { margin-top:1px; color:#8aa39f; font-size:6px; }.activity-value { color:#0b8d62; font-size:7px; font-weight:800; }.dashboard figcaption { margin-top:11px; color:#54706d; font-size:10px; text-align:center; }
        .features { padding:82px 0; background:#fff; border-top:1px solid var(--line); }.section-intro { max-width:610px; }.kicker { color:#08776e; font-size:.8rem; font-weight:800; letter-spacing:.08em; text-transform:uppercase; }.features h2,.cta h2 { margin:11px 0; font-family:Fraunces,Georgia,serif; font-size:clamp(2rem,3.4vw,3rem); letter-spacing:-.04em; }.section-intro p { color:var(--muted); line-height:1.6; } .grid { display:grid; grid-template-columns:repeat(4,1fr); gap:16px; margin-top:35px; }.feature { padding:25px; border:1px solid var(--line); border-radius:14px; background:#fcfefd; }.feature-icon { display:grid; place-items:center; width:38px; height:38px; border-radius:10px; background:var(--mint); color:#076f66; font-weight:800; }.feature h3 { margin:17px 0 8px; font-size:1.05rem; }.feature p { margin:0; color:var(--muted); font-size:.92rem; line-height:1.58; } .feature-alert .feature-icon { background:#fff0d4; color:#a35b06; }
        .cta { padding:82px 0; text-align:center; }.cta p { max-width:500px; margin:0 auto 23px; color:var(--muted); line-height:1.6; }.footer { padding:25px 0 35px; border-top:1px solid var(--line); color:#66807c; font-size:.86rem; }.footer .shell { display:flex; justify-content:space-between; } @media (min-width:761px) and (max-width:900px) { .grid{grid-template-columns:repeat(2,1fr)} } @media (max-width:760px) { .nav-links a:not(.button){display:none}.hero{grid-template-columns:1fr;gap:45px;padding:52px 0 70px}.dashboard{max-width:500px;margin:auto}.grid{grid-template-columns:1fr}.proof{gap:12px;flex-direction:column}.footer .shell{gap:9px;flex-direction:column}.screen-body{min-height:265px} }
    </style>
</head>
<body>
    <header class="shell nav"><a class="brand" href="{{ route('home') }}" aria-label="{{ config('app.name', 'POS') }} home"><img class="mark" src="{{ asset('favicon.svg') }}" alt="" aria-hidden="true">{{ config('app.name', 'POS') }}</a><nav class="nav-links" aria-label="Main navigation"><a href="#features">Features</a>@auth <a href="{{ route('dashboard') }}" class="button button-primary">Open dashboard</a> @else <a href="{{ route('login') }}">Log in</a><a href="{{ route('register') }}" class="button button-primary">Get started</a> @endauth</nav></header>
    <main><section class="shell hero" aria-labelledby="hero-heading"><div><span class="eyebrow"><i></i> Built for growing local businesses</span><h1 id="hero-heading">Run your shop with clarity, not clutter.</h1><p class="lead">{{ config('app.name', 'POS') }} brings your sales, inventory, products, and team together in one straightforward point-of-sale system.</p><div class="actions">@auth <a class="button button-primary" href="{{ route('dashboard') }}">Open your dashboard →</a> @else <a class="button button-primary" href="{{ route('register') }}">Create your account →</a><a class="button button-secondary" href="#features">Explore features</a> @endauth</div><div class="proof"><span>Fast checkout</span><span>Live inventory</span><span>Team-ready</span></div></div>
    <figure class="dashboard" aria-label="{{ config('app.name', 'POS') }} dashboard product preview with illustrative data"><div class="screen"><div class="product-bar"><div class="product-brand"><span>▣</span>{{ config('app.name', 'POS') }}</div><i class="product-user"></i></div><div class="screen-body"><aside class="side"><a class="active">Dashboard</a><a>Products</a><a>Sales</a><a>Point of Sale</a><a>Analytics</a></aside><div class="workspace"><div class="workspace-head"><div><div class="screen-title">Dashboard</div><div class="screen-sub">Your shop at a glance</div></div><span class="date-chip">Today</span></div><div class="stats"><div class="stat"><small>Total Revenue</small><strong>₱24,580</strong><span class="up">↑ 12% this week</span></div><div class="stat"><small>Total Orders</small><strong>128</strong><span class="up">↑ 8% this week</span></div><div class="stat stock-alert"><small>Low Stock</small><strong>6 items</strong><span class="up">Needs attention</span></div><div class="stat"><small>Avg. Order</small><strong>₱192</strong><span class="up">↑ 4% this week</span></div></div><div class="activity"><h3>Recent Stock Activity</h3><div class="activity-row"><i class="activity-icon"></i><div class="activity-copy"><b>Iced Coffee · Medium</b><span>Stock received</span></div><span class="activity-value">+24</span></div><div class="activity-row"><i class="activity-icon"></i><div class="activity-copy"><b>Milk Tea · Vanilla</b><span>Sale completed</span></div><span class="activity-value">−3</span></div></div></div></div></div><figcaption>Product preview — illustrative data only</figcaption></figure></section>
    <section id="features" class="features" aria-labelledby="features-heading"><div class="shell"><div class="section-intro"><span class="kicker">Everything in one place</span><h2 id="features-heading">The essentials your counter needs.</h2><p>Keep daily operations moving with practical tools designed around the way small retail teams actually work.</p></div><div class="grid"><article class="feature"><div class="feature-icon">↗</div><h3>Quick checkout</h3><p>Build orders and complete sales without slowing down the queue.</p></article><article class="feature"><div class="feature-icon">▤</div><h3>Inventory control</h3><p>Track stock movements and spot items that need attention before they run out.</p></article><article class="feature feature-alert"><div class="feature-icon">!</div><h3>Low stock alerts</h3><p>Know which items need attention before an empty shelf costs you a sale.</p></article><article class="feature"><div class="feature-icon">◌</div><h3>Clear reporting</h3><p>See sales performance and product activity in a dashboard your team can understand.</p></article></div></div></section>
    <section class="cta"><div class="shell"><span class="kicker">Start simply</span><h2>Spend less time managing the shop.</h2><p>Set up your products, invite your team, and keep every sale and stock update in view.</p>@guest <a class="button button-primary" href="{{ route('register') }}">Get started with {{ config('app.name', 'POS') }} →</a> @endguest</div></section></main>
    <footer class="footer"><div class="shell"><span>© {{ now()->year }} {{ config('app.name', 'POS') }}. All rights reserved.</span><a href="{{ route('login') }}">Log in</a></div></footer>
</body>
</html>
