import { Head, Link, useForm, usePage } from '@inertiajs/react';
import AdminLayout from '@/Layouts/AdminLayout';
import { PageProps } from '@/types';
import { Banknote, CheckCircle2, CircleDollarSign } from 'lucide-react';

type Shift = { id: number; opening_float: string; closing_cash: string | null; expected_cash: string | null; variance: string | null; opened_at: string; closed_at: string | null; notes: string | null };
interface Props extends PageProps { active: Shift | null; history: Shift[]; }
const money = (value: string | number | null) => `P${Number(value ?? 0).toLocaleString('en-PH', { minimumFractionDigits: 2 })}`;

export default function Shifts({ active, history }: Props) {
    const shop = usePage<PageProps>().props.currentShop?.slug ?? '';
    const open = useForm({ opening_float: '' });
    const close = useForm({ closing_cash: '', notes: '' });
    return <AdminLayout header={<div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold text-[#102a2a] dark:text-white">Cash Shifts</h1><p className="mt-1 text-sm text-[#54706d] dark:text-gray-400">Open, count, and reconcile your cash drawer.</p></div><Link href={`/${shop}/pos`} className="text-sm text-[#0f766e]">Back to POS</Link></div>}>
        <Head title="Cash Shifts" />
        <div className="mx-auto max-w-3xl space-y-6">
            {!active ? <section className="rounded-xl border border-[#d9e8e5] bg-white p-6 dark:border-gray-700 dark:bg-gray-800"><div className="flex gap-3"><div className="rounded-lg bg-[#d7f3ed] p-2 text-[#0f766e]"><CircleDollarSign /></div><div><h2 className="font-semibold dark:text-white">Open a cash shift</h2><p className="mt-1 text-sm text-[#54706d] dark:text-gray-400">Count the starting cash in your drawer before taking cash sales.</p></div></div><form onSubmit={e => { e.preventDefault(); open.post(`/${shop}/pos/shifts/open`); }} className="mt-5 flex gap-3"><input required type="number" min="0" step="0.01" value={open.data.opening_float} onChange={e => open.setData('opening_float', e.target.value)} placeholder="Opening float" className="flex-1 rounded-lg border border-[#d9e8e5] bg-white px-3 py-2 dark:bg-gray-700" /><button className="rounded-lg bg-[#0f766e] px-4 py-2 text-sm font-semibold text-white">Open shift</button></form>{open.errors.opening_float && <p className="mt-2 text-sm text-red-600">{open.errors.opening_float}</p>}</section> : <section className="rounded-xl border border-[#d9e8e5] bg-white p-6 dark:border-gray-700 dark:bg-gray-800"><div className="flex gap-3"><div className="rounded-lg bg-[#d7f3ed] p-2 text-[#0f766e]"><Banknote /></div><div><h2 className="font-semibold dark:text-white">Active shift</h2><p className="mt-1 text-sm text-[#54706d] dark:text-gray-400">Opened {new Date(active.opened_at).toLocaleString('en-PH')} · Float {money(active.opening_float)}</p></div></div><form onSubmit={e => { e.preventDefault(); close.post(`/${shop}/pos/shifts/close`); }} className="mt-5 space-y-3"><input required type="number" min="0" step="0.01" value={close.data.closing_cash} onChange={e => close.setData('closing_cash', e.target.value)} placeholder="Counted cash in drawer" className="w-full rounded-lg border border-[#d9e8e5] bg-white px-3 py-2 dark:bg-gray-700" /><input value={close.data.notes} onChange={e => close.setData('notes', e.target.value)} placeholder="Optional note" className="w-full rounded-lg border border-[#d9e8e5] bg-white px-3 py-2 dark:bg-gray-700" /><button className="rounded-lg bg-[#0f766e] px-4 py-2 text-sm font-semibold text-white">Close & reconcile</button></form></section>}
            <section className="overflow-hidden rounded-xl border border-[#d9e8e5] bg-white dark:border-gray-700 dark:bg-gray-800"><div className="border-b border-[#d9e8e5] px-5 py-3"><h2 className="font-semibold dark:text-white">Recent shifts</h2></div><div className="divide-y divide-[#d9e8e5]">{history.map(shift => <div key={shift.id} className="flex items-center justify-between px-5 py-4 text-sm"><div><p className="font-medium dark:text-white">{new Date(shift.opened_at).toLocaleDateString('en-PH')}</p><p className="text-xs text-[#54706d]">Float {money(shift.opening_float)}{shift.closed_at ? ` · Expected ${money(shift.expected_cash)}` : ' · Active'}</p></div>{shift.closed_at ? <span className={`inline-flex items-center gap-1 font-semibold ${Number(shift.variance) === 0 ? 'text-emerald-600' : 'text-amber-600'}`}><CheckCircle2 className="h-4 w-4" />{Number(shift.variance) === 0 ? 'Balanced' : `${Number(shift.variance) > 0 ? '+' : ''}${money(shift.variance)}`}</span> : <span className="text-[#0f766e]">Open</span>}</div>)}</div></section>
        </div>
    </AdminLayout>;
}
